### ISSUE TITLE
Can't efficiently construct from already validated utf8

### ISSUE THREAD

**Issue by arthurprs** [carllerche/string#6]
There's no safe and efficient way of building String<Vec<u8>> or String<Bytes> without re-validating the underlying bytes. Ideally these should compile and don't re-validate the utf8 sequence.

``` 
let _: String<Vec<u8>> = "hello".into();
let _: String<Bytes> = "hello".into();
```

We can't have this

```
impl<'a, T: From<&'a [u8]>> From<&'a str> for String<T>
```

because it conflicts with the existing

```
impl From<::std::string::String> for String<::std::string::String>
impl<'a> From<&'a str> for String<&'a str>
```

Unfortunately I don't know any way around it without removing the existing impls above, but maybe we should as String<&str> and String<String> aren't exactly the most useful use cases IMHO.

**Comment by arthurprs** [comment]
We could get away adding a from_str(&str) method.

**Comment by carllerche** [comment]
Good point. Could this work?

```rust
impl<T> String<T> {
    fn from_str<'a>(src: &'a str) -> String<T>
    where T: From<&'a str>,
    { ... }
}
```

**Comment by arthurprs** [comment]
I think the bounds should be mostly about [u8].
If it can be a breaking change it could follow std::str to some extent:
```
fn from_utf8<'a>(src: &'a str) -> String<T> where From<&'a [u8]>
fn from_utf8_unchecked<'a>(src: &'a [u8]) -> String<T> where From<&'a [u8]>
fn from_unchecked(src: T) -> String<T>
```

**Comment by carllerche** [comment]
Using `&[u8]` as the bound for `from_str` sounds good to me, 

I don't think we need two `_unchecked` variants. The first one can be obtained by doing `String::from_unchecked(src.into())` I believe.

**Comment by arthurprs** [comment]
Yeah `from_unchecked(src.into())` should work for a plain byte slice too.

**Comment by carllerche** [comment]
Will you submit a PR? :)

**Comment by arthurprs** [comment]
I'll :grinning:
